#!/bin/bash
# Bootstraps the optional, BYO-download ONNX models AgentGuard uses for its gated E2E tests and the
# ONNX/PII samples, pulling the prebuilt exports straight from Hugging Face. The Defender prompt
# injection model is bundled in the package and needs no download - it is NOT fetched here.
#
# This is a thin orchestrator over the per-model eng/download-*.sh scripts: it downloads each model
# into ./models/<name> and writes a single sourceable env file (./models/env.sh) exporting the
# AGENTGUARD_*_PATH variables the tests and samples read.
#
# Usage:
#   ./bootstrap-models.sh                  # download all models (~1.9 GB)
#   ./bootstrap-models.sh gliner           # just the PII NER model
#   ./bootstrap-models.sh gliner opir      # a subset
#
# Models: gliner (PII NER), opir (multilingual content safety), piguard (injection),
#         deberta (generic BYO injection classifier).
#
# Then, to run the gated tests/samples in the current shell:
#   source ./models/env.sh
#   dotnet test AgentGuard.slnx
#
# Re-running is cheap: each model is skipped if already present. Output dir override: MODELS_DIR=...
# Everything lands under ./models, which is gitignored.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODELS_DIR="${MODELS_DIR:-$ROOT_DIR/models}"
ENV_FILE="$MODELS_DIR/env.sh"

ALL_MODELS=(gliner opir piguard deberta)

# pick the requested models (default: all)
if [ "$#" -eq 0 ]; then
    SELECTED=("${ALL_MODELS[@]}")
else
    SELECTED=()
    for arg in "$@"; do
        case "$arg" in
            all) SELECTED=("${ALL_MODELS[@]}") ;;
            gliner|opir|piguard|deberta) SELECTED+=("$arg") ;;
            *)
                echo "Unknown model '$arg'. Valid: ${ALL_MODELS[*]} all" >&2
                exit 2
                ;;
        esac
    done
fi

mkdir -p "$MODELS_DIR"

# maps a model key to its eng download script and target subdirectory
download_model() {
    local key="$1"
    case "$key" in
        gliner)  "$ROOT_DIR/eng/download-gliner-model.sh"  "$MODELS_DIR/gliner" ;;
        opir)    "$ROOT_DIR/eng/download-opir-model.sh"    "$MODELS_DIR/opir-multilang" ;;
        piguard) "$ROOT_DIR/eng/download-piguard-model.sh" "$MODELS_DIR/piguard" ;;
        deberta) "$ROOT_DIR/eng/download-onnx-model.sh"    "$MODELS_DIR/deberta-v3-prompt-injection" ;;
    esac
}

for key in "${SELECTED[@]}"; do
    echo ""
    echo "==> $key"
    download_model "$key"
done

# (re)generate the env file from whatever models are present on disk, so a partial bootstrap still
# yields a complete, sourceable env for everything that has been downloaded.
emit_export() {
    # emit_export VAR FILE  -> appends an export line if FILE exists
    local var="$1" file="$2"
    if [ -f "$file" ]; then
        echo "export $var=\"$file\"" >> "$ENV_FILE"
    fi
}

echo "# generated by bootstrap-models.sh - source this to run the gated AgentGuard tests/samples" > "$ENV_FILE"

emit_export AGENTGUARD_GLINER_ONNX_MODEL_PATH "$MODELS_DIR/gliner/model.onnx"
emit_export AGENTGUARD_GLINER_TOKENIZER_PATH  "$MODELS_DIR/gliner/spm.model"
emit_export AGENTGUARD_GLINER_CONFIG_PATH     "$MODELS_DIR/gliner/config.json"

emit_export AGENTGUARD_OPIR_ONNX_MODEL_PATH   "$MODELS_DIR/opir-multilang/model.onnx"
emit_export AGENTGUARD_OPIR_TOKENIZER_PATH    "$MODELS_DIR/opir-multilang/spm.model"
emit_export AGENTGUARD_OPIR_PREFIX_PATH       "$MODELS_DIR/opir-multilang/prefix.json"

emit_export AGENTGUARD_PIGUARD_ONNX_MODEL_PATH "$MODELS_DIR/piguard/model.onnx"
emit_export AGENTGUARD_PIGUARD_TOKENIZER_PATH  "$MODELS_DIR/piguard/spm.model"

emit_export AGENTGUARD_ONNX_MODEL_PATH        "$MODELS_DIR/deberta-v3-prompt-injection/model.onnx"
emit_export AGENTGUARD_ONNX_TOKENIZER_PATH    "$MODELS_DIR/deberta-v3-prompt-injection/spm.model"

echo ""
echo "Done. Wrote env exports to $ENV_FILE"
echo "To use them in the current shell:"
echo "  source ${ENV_FILE/#$ROOT_DIR\//./}"
